substitutions:
  # Import Config
  import_config: "true"
  # Logger Level - Can use VERBOSE for more information in Logs
  logger: "DEBUG"

  # I2C pins
  sdaPin: "21" # yellow/TX PMP-green
  sclPin: "22" # blue/RX PMP-white

esphome:
  min_version: 2024.6.0
  name: "${name}"
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  name_add_mac_suffix: true
  comment: "Raph's Reef ESP32 - Moniteur d'aquarium"
  project:
    name: twinsen68.raphsreef
    version: "${app_version}"
    
# Enable logging
logger:
  level: "${logger}"

api:

ota:
  - platform: esphome

wifi:
  ssid: "Votre_SSID"  # Réseau principal
  password: "Votre_Mot_De_Passe"  # Mot de passe du réseau principal

  ap:
    ssid: "AquapiGPT_Recovery"  # Nom du réseau Access Point en mode secours
    password: "MotDePasse_AP"  # Mot de passe pour l'accès direct

captive_portal:

web_server:
#   version: 3
  
improv_serial:

# i2c Pins
i2c:
  sda: ${sdaPin}
  scl: ${sclPin}
  scan: true
  id: bus_a

# Internal Blue LED
light:
  - platform: status_led
    id: led_interne
    pin:
      number: GPIO2
      ignore_strapping_warning: true

sensor:
  # Internal Temp.
  - platform: internal_temperature
    name: "Température interne"

  # Wifi Signal 
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi - Signal dB"
    disabled_by_default: true
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  # Wifi %
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi force du signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  # Uptime sensor
  - platform: uptime
    name: Dernier démarage 

  # Internal Magnetic Sensor
  - platform: esp32_hall
    name: "ESP32 Hall"
    entity_category: "diagnostic"

  # of I2C devices connected
  - platform: template
    name: "I2C Devices Connected"
    id: i2c_devices
    icon: mdi:integrated-circuit-chip
    entity_category: "diagnostic"
    # disabled_by_default: true
    lambda: |-
      byte error, address;
      int nDevices;
      nDevices = 0;
      for(address = 1; address < 127; address++) {
        Wire.beginTransmission(address);
        error = Wire.endTransmission();
        if (error == 0) {
          nDevices++;
        }
      }
      return nDevices;

binary_sensor:
  # API Status
  - platform: status
    name: "Status"

text_sensor:
  # Hostname
  - platform: template
    name: "Nom du device"
    id: hostname
    icon: mdi:cellphone-arrow-down
    lambda: |-
      return {"${name}"};
    entity_category: "diagnostic"

  # Wifi Info
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network
    ssid:
      name: SSID
      icon: mdi:wifi-arrow-left-right
    bssid:
      name: BSSID
      icon: mdi:wifi-star
      disabled_by_default: true
    mac_address:
      name: Address Mac
      icon: mdi:chip

button:
  # Soft Restart
  - platform: restart
    id: restart_button
    name: "Rédemarer"

  # Factory Reset
  - platform: factory_reset
    name: Réintial. Usine 
    disabled_by_default: true

  # Safe Mode Restart
  - platform: safe_mode
    name: "Safe Mode"
    id: restart_safe

  # Shutdown
  - platform: shutdown
    name: "Eteindre"
    disabled_by_default: true
    id: shutdown_button

time:
  - platform: sntp
    id: sntp_time  # Identifiant SNTP pour les automatisations
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
    timezone: "Europe/Paris"  # Fuseau horaire

interval:
  - interval: 5min  # Vérifie toutes les 5 minutes
    then:
      - if:
          condition:
            wifi.connected: false  # Déclenche si le Wi-Fi est déconnecté
          then:
            - logger.log: "Wi-Fi non connecté. Redémarrage en cours..."  # Log l'événement
            - delay: 30s  # Attente avant redémarrage
            - reboot:  # Redémarrage de l'ESP
