substitutions:
  update_firmware_sensor_interval: 6h

ota:
  - platform: http_request

http_request:
  verify_ssl: false

# update:
#   - platform: http_request
#     name: raphsreef Firmware Update
#     update_interval: "${update_firmware_sensor_interval}"
#     id: update_firmware_sensor
#     entity_category: 'diagnostic'
#     icon: mdi:update
#     source: https://raw.githubusercontent.com/Twinsen68/raph/gh-pages/manifest.json

button:
  - platform: template
    id: update_firmware
    name: Update raphsreef Firmware - Releaseed (Experimental - ESP32)
    entity_category: "config"
    icon: mdi:update
    # disabled_by_default: true
    on_press: 
      then:
        - ota.http_request.flash:
            md5_url: https://raw.githubusercontent.com/Twinsen68/raphreef/main/bin/ota/raphsreef-esp32.ota.md5
            url: https://raw.githubusercontent.com/Twinsen68/raphreef/main/bin/ota/raphsreef-esp32.ota.bin