text_sensor: 
  # raphsreef Version
  - platform: template
    name: "raphsreef Version"
    id: raphsreef_version
    icon: mdi:update
    update_interval: '365days'
    lambda: |-
      return {"${app_version}"};
    entity_category: "diagnostic"

  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    update_interval: '365days'
    lambda: |-
      return {"github.com/twinsen68/raphreef"};
    entity_category: "diagnostic"

  # Déclaration d'un capteur textuel pour afficher l'heure actuelle synchronisée via SNTP
  - platform: template
    name: "Heure actuelle"  # Nom visible dans Home Assistant pour ce capteur
    lambda: |-
      // Vérifie si l'instance SNTP a une heure valide synchronisée
      if (id(sntp_time).now().is_valid()) {
        // Si oui, retourne l'heure actuelle au format HH:MM:SS (heure:minute:seconde)
        return id(sntp_time).now().strftime("%H:%M:%S");
      } else {
        // Si non, indique que l'heure n'est pas synchronisée
        return {"Non synchronisé"};
      }
    icon: mdi:clock  # Icône représentant une horloge, utilisée pour un affichage clair dans Home Assistant

time:
  # Synchronisation horaire pour la gestion des cycles 24h
  - platform: sntp
    id: sntp_time

automation:
  # Notification lorsque le Wi-Fi est déconnecté
  - alias: "Wi-Fi déconnecté"
    trigger:
      - platform: wifi  # Déclencheur Wi-Fi de ESPHome
        event: disconnected  # Événement : déconnexion
    action:
      - logger.log: "Attention ! Wi-Fi déconnecté."  # Journal de l'événement
      - text_sensor.template.publish:
          id: wifi_status_text  # Mise à jour du statut
          state: "Déconnecté"

  # Notification lorsque le Wi-Fi est reconnecté
  - alias: "Wi-Fi reconnecté"
    trigger:
      - platform: wifi  # Déclencheur Wi-Fi de ESPHome
        event: connected  # Événement : connexion réussie
    action:
      - logger.log: "Wi-Fi reconnecté avec succès."  # Journal de l'événement
      - text_sensor.template.publish:
          id: wifi_status_text
          state: "Connecté"